# Generated by Django 5.0 on 2024-01-21 15:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magasin', '0008_remove_transfert_id_transfert_codetransfert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('CodeCentre', models.AutoField(primary_key=True, serialize=False)),
                ('DesignationCentre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('CodeC', models.AutoField(primary_key=True, serialize=False)),
                ('nomPrenomC', models.CharField(max_length=60)),
                ('adresseC', models.CharField(max_length=60)),
                ('telephoneC', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('produit', models.AutoField(primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=40)),
                ('qteStock', models.PositiveIntegerField()),
                ('HTProd', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('CodeE', models.AutoField(primary_key=True, serialize=False)),
                ('nomPrenomE', models.CharField(max_length=60)),
                ('adresseE', models.CharField(max_length=60)),
                ('telephoneE', models.CharField(max_length=20)),
                ('salaireJour', models.IntegerField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('codeA', models.AutoField(primary_key=True, serialize=False)),
                ('montantAvance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateAvance', models.DateField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('codeA', models.AutoField(primary_key=True, serialize=False)),
                ('dateAbsence', models.DateField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('CodeReg', models.AutoField(primary_key=True, serialize=False)),
                ('montantReg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateReg', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.client')),
            ],
        ),
        migrations.CreateModel(
            name='TransfertRecu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTransfert', models.DateField()),
                ('qteTransfert', models.IntegerField()),
                ('cost', models.IntegerField(default=0)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.centre')),
                ('produitTr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('CodeV', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('PayEnt', models.BooleanField(default=True)),
                ('qteVente', models.IntegerField(default=0)),
                ('prixUniVente', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_total', models.IntegerField(default=0)),
                ('montant_paye', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.produit')),
            ],
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('CodePayCredit', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.client')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.vente')),
            ],
        ),
    ]
