# Generated by Django 5.0 on 2024-01-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('CodeReg', models.AutoField(primary_key=True, serialize=False)),
                ('montantReg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateReg', models.DateField()),
                ('credit_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.creditpayment')),
            ],
        ),
    ]
