# Generated by Django 5.0 on 2024-01-02 18:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('codeA', models.AutoField(primary_key=True, serialize=False)),
                ('dateArrivee', models.DateTimeField(default=datetime.datetime(2024, 1, 2, 19, 19, 34, 929425))),
                ('presence', models.BooleanField(null=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.employe')),
            ],
        ),
    ]
