# Generated by Django 5.0 on 2024-01-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditpayment',
            old_name='client',
            new_name='clientc',
        ),
    ]
