# Generated by Django 5.0 on 2023-12-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='CodeP',
            new_name='produit_id',
        ),
    ]
