# Generated by Django 5.0 on 2024-01-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='dateArrivee',
            field=models.DateField(),
        ),
    ]
