# Generated by Django 5.0 on 2023-12-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_rename_codep_produit_produit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='produit_id',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='produit_id',
            new_name='produit',
        ),
    ]
