# Generated by Django 5.0 on 2024-01-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_vente_payent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglement',
            name='credit',
        ),
    ]
