# Generated by Django 5.0 on 2024-01-20 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_reglement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglement',
            name='credit_payment',
        ),
        migrations.AddField(
            model_name='reglement',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='centre.client'),
            preserve_default=False,
        ),
    ]
