# Generated by Django 5.0 on 2023-12-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_vente_prix_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
