# Generated by Django 5.0 on 2024-01-02 19:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0003_alter_attendance_datearrivee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('codeA', models.AutoField(primary_key=True, serialize=False)),
                ('montantAvance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateAvance', models.DateField(default=datetime.datetime(2024, 1, 2, 20, 0, 41, 576854))),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.employe')),
            ],
        ),
    ]
