# Generated by Django 5.0 on 2023-12-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0003_rename_produit_id_produit_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='PayeEnt',
            field=models.BooleanField(null=True),
        ),
    ]
