# Generated by Django 5.0 on 2024-01-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0003_remove_reglement_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='credit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='centre.creditpayment'),
            preserve_default=False,
        ),
    ]
