# Generated by Django 5.0 on 2023-12-29 00:16

import centre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0003_alter_creditpayment_date_alter_vente_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.CharField(max_length=8, validators=[centre.models.validate_date_format]),
        ),
    ]
