# Generated by Django 5.0 on 2023-12-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0004_alter_vente_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateField(),
        ),
    ]
