# Generated by Django 5.0 on 2024-01-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0004_reglement_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='montant_paye',
            field=models.IntegerField(default=0),
        ),
    ]
