# Generated by Django 5.0 on 2024-01-02 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0005_alter_avance_dateavance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('codeA', models.AutoField(primary_key=True, serialize=False)),
                ('dateAbsence', models.DateField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.employe')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
