# Generated by Django 5.0 on 2023-12-29 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0005_alter_creditpayment_date_alter_vente_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='prixUniV',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='prix_total',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='quantiteV',
        ),
        migrations.CreateModel(
            name='ProduitVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qteVente', models.IntegerField()),
                ('prixUniVente', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.vente')),
            ],
        ),
    ]
