# Generated by Django 5.0 on 2023-12-29 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0006_remove_vente_prixuniv_remove_vente_prix_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='prixUniVente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vente',
            name='prix_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(default='VotreValeurParDefaut', on_delete=django.db.models.deletion.CASCADE, to='centre.produit'),
        ),
        migrations.AddField(
            model_name='vente',
            name='qteVente',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProduitVente',
        ),
    ]
