# Generated by Django 5.0 on 2023-12-29 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0007_vente_prixunivente_vente_prix_total_vente_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='centre.produit'),
        ),
    ]
