# Generated by Django 5.0 on 2023-12-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0008_alter_vente_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.produit'),
        ),
    ]
