# Generated by Django 5.0 on 2023-12-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0009_alter_vente_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='produit',
        ),
    ]
