# Generated by Django 5.0 on 2023-12-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0010_remove_vente_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='centre.produit'),
            preserve_default=False,
        ),
    ]
