# Generated by Django 5.0 on 2024-01-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('CodeCentre', models.AutoField(primary_key=True, serialize=False)),
                ('DesignationCentre', models.CharField(max_length=40)),
            ],
        ),
    ]
