# Generated by Django 5.0 on 2024-01-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditpayment',
            old_name='date',
            new_name='dateP',
        ),
    ]
