# Generated by Django 5.0 on 2024-01-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre2', '0002_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='centre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='centre2.centre'),
            preserve_default=False,
        ),
    ]
