# Generated by Django 5.0 on 2024-01-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre2', '0002_rename_date_creditpayment_datep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='codeA',
            new_name='codeAb',
        ),
    ]
