# Generated by Django 5.0 on 2023-12-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='solde',
            field=models.IntegerField(default=0),
        ),
    ]
