# Generated by Django 5.0 on 2023-12-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_alter_client_credit_alter_fournisseur_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='qteStock',
            field=models.IntegerField(default=0),
        ),
    ]
