# Generated by Django 5.0 on 2023-12-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_transfert_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='produits',
            field=models.ManyToManyField(related_name='produits', to='magasin.produit'),
        ),
    ]
