# Generated by Django 5.0 on 2023-12-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_achat_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='produits',
        ),
    ]
