# Generated by Django 5.0 on 2024-01-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_remove_achat_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitvente',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produitvente',
            name='vente',
        ),
        migrations.AddField(
            model_name='achat',
            name='HTAchat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achat',
            name='produit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='magasin.produit'),
        ),
        migrations.AddField(
            model_name='achat',
            name='qteAchat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vente',
            name='prixUniVente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='magasin.produit'),
        ),
        migrations.AddField(
            model_name='vente',
            name='qteVente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='HTProd',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProduitAchat',
        ),
        migrations.DeleteModel(
            name='ProduitVente',
        ),
    ]
