# Generated by Django 5.0 on 2024-01-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_remove_produitvente_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfert',
            name='id',
        ),
        migrations.AddField(
            model_name='transfert',
            name='CodeTransfert',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
